* editor
** mettre le titre de l'assemblage a coté des boutons pour le modifier
** rendre le role des boutons plus clair
par exemple en mettant les boutons de l'animation à coté de son nom, ou les mettre dans un bloc visuel
** collapsing textareas
** mecanisme pour signaler les animations à enregistrer
* exquis
** remplacer setInterval par requestAnimation
* editorController
** editorController et editorView se connaissent mutuellement
*** construction 
le controller devient une usine de controller.
l'usine est créé avec exquis en argument.
la view est créée avec l'usine de controller en argument.
elle crée le controller en se donnant en argument a l'usine.

*** virer tous les callbacks donnés par la vue
En ce moment (presque) toutes les actions du controller se font par callbacks.
Remplacer ça par des appels aux méthodes de la vue
* new animations
* bugs
* implement blockly interface https://code.google.com/p/blockly/
* allow usage of files from external urls (github.com, pastebin, etc)
define a assemblage file with urls

* refactor dashboard so it can be included in a jsfiddle
so that jsfiddle's javascript editor can be used to write animations or assemblages
* faire en sorte que ça tourne sans serveur (ni internet?)
avoir des animations par defaut dans des fichiers javascripts chargés par index.html
* include
** catch onScriptError (require.js) pour choper quand l'addresse est invalide ou le serveur injoignable
** qu'est ce qui se passe quand le code de la lib est invalide
** bug: class invalid sur le textArea des libs restent rouge même quand on sélectionne une autre animation (valide)
* new syntax format
** evalEvil prend une animation sous la forme suivante (string)
http://stackoverflow.com/questions/20838067/catch-js-errors-when-adding-a-script-dynamically
"x.animate(function(){
   var i = 0;
   return {
      libs:{"http:/burp", "burp"},
      setup: function(ctx, borders, libs){...},
      draw: function(ctx, borders, libs){...}
   };
});"

"animate({
      libs:{"http:/burp", "burp"},
      setup: function(ctx, borders, libs){...},
      draw: function(ctx, borders, libs){...}
   });"

donc il va falloir passer les librairies en argument
au lieu de les coller à this.
